### ISSUE TITLE
Aer executable

### ISSUE THREAD

**Issue by feamsr00** [belliash/AerScript#2]
Hi There!

This is a very interesting project and I wanted to run some cursory tests. I know it's early stages, but might I suggest/request regular ci builds?

**Comment by belliash** [comment]
Hello,

Actually, we do not plan regular builds. Unfortunately, you have to build it on your own.

**Comment by feamsr00** [comment]
Hi @belliash. I suppose I don't mind building it on my own if I could ask about your precise build chain.

First off, could I ask you what version of make you use? And your windows tests\builds.  Mingw? Cygwin? Plain GCC toolkit?
