### ISSUE TITLE
Allow expressions in include/require

### ISSUE THREAD

**Issue by secondtruth** [belliash/AerScript#3]
# AerScript Information
 - Aer Version (or commit ref): 5e6ed0f6682a4cb71695608c589b53107022835e
 - Operating System: Ubuntu
 - System Architecture (eg. arm, x86_64, ...): x86_64

# Your problem description
Expressions in include/require should be allowed:

    include __DIR__ + '/file.aer';

# Expected results
File with absolute path included

# Current results
Error: Unexpected token `__DIR__`

**Comment by belliash** [comment]
Since __DIR__ points to directory with currently running script, it should be sufficient to use the following syntax and include file with relative path: `include 'file.aer';`

**Comment by secondtruth** [comment]
If all scripts are located in the same directory  then you're right. But when the included files are located in another directory and they include files themselves this doesn't work, because `include`/`require` is always relative to the directory of the top script file.

Using `__DIR__` could be one solution, because actually `__DIR__` points to the directory of the file where it is used. So, in included files `__DIR__` points to the directory of the included file. Another solution would be to rewrite `include`/`require` to behave like `__DIR__`.

Another use case for expressions in `require` would be in autoloaders to include files based on class name.
